# Generated by Django 4.0 on 2022-04-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todocategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
