# Generated by Django 4.0 on 2022-04-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todocategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
